In [1]:
#레포트 2-1
import numpy as np
temp = np.array(range(1,65))
original_arr = temp.reshape(8,8)
print(original_arr)
reshaped_arr = temp.reshape(8,4,2)
print(reshaped_arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]

 [[33 34]
  [35 36]
  [37 38]
  [39 40]]

 [[41 42]
  [43 44]
  [45 46]
  [47 48]]

 [[49 50]
  [51 52]
  [53 54]
  [55 56]]

 [[57 58]
  [59 60]
  [61 62]
  [63 64]]]


In [2]:
#레포트 2-2
A = np.array(range(1,10001))
B = A[A % 2 == 0, ]
print(A)
print(B)

[    1     2     3 ...  9998  9999 10000]
[    2     4     6 ...  9996  9998 10000]


In [3]:
#레포트 2-3
from google.colab import drive

drive.mount("/content/drive")
train_data_path = "/content/drive/My Drive/colab_data/baduk/train_data.npy"
train_label_path = "/content/drive/My Drive/colab_data/baduk/train_label.npy"

train_data = np.load(train_data_path, allow_pickle = True)
train_label_rawdata = np.load(train_label_path, allow_pickle = True)

num_train_data = len(train_data)

Mounted at /content/drive


In [4]:
print(train_data.shape)

(2682,)
